version: '3'
services:
  cardano-api:
    build:
      context: .
      target: build
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    command: npm run start:dev
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    env_file: .env
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - .:/opt/node_app/app/
      - $HOME/.aws/credentials:/home/node/.aws/credentials
      - /opt/node_app/app/node_modules # anonymous volume for node_modules only

  redis:
    image: redis:6.2.6
    command: redis-server
    ports:
      - target: 6379
        published: 6377
        protocol: tcp
        mode: host