version: '3'

services:
  some-scylla:
    image: scylladb/scylla
    container_name: some-scylla
    command:
      - --alternator-port 8000
      - --alternator-write-isolation always
    volumes:
      - /var/lib/scylla:/var/lib/scylla

  # some-scylla2:
  #   image: scylladb/scylla
  #   container_name: some-scylla2
  #   command: --seeds=some-scylla

  # some-scylla3:
  #   image: scylladb/scylla
  #   container_name: some-scylla3